<?php

/**
 * @file
 * Update paths when a menu item is moved.
 */

/**
 * Implements hook_menu_link_update().
 */
function pathauto_menu_link_menu_link_update($link) {
  $href = $link['href'];
  $exploded = explode('/', $href);
  if ($exploded) {
    if ($exploded[0] == 'node') { // Only affect nodes.
      // Get the node ID and load the node object.
      $nid = $exploded[1];
      $node = node_load($nid);

      // @todo: Check that the path has changed before updating the node.

      // Update the alias.
      pathauto_node_update_alias($node, 'update');
    }
  }
}
